status = [
  "test-os (ubuntu-latest)",
  "test-os (windows-latest)",
  "test-os (macos-latest)",
  "buildkite/climatemachine-ci",
  "docs-build",
  "format"
]
delete_merged_branches = true
timeout_sec = 10800
block_labels = [ "do-not-merge-yet" ]
cut_body_after = "<!--"
