name = "ClimateMachine"
uuid = "777c4786-024f-11e9-21a3-85d5d4106250"
authors = ["Climate Modeling Alliance"]
version = "0.3.0-DEV"

[deps]
Adapt = "79e6a3ab-5dfb-504d-930d-738a2a938a0e"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
ArtifactWrappers = "a14bc488-3040-4b00-9dc1-f6467924858a"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CLIMAParameters = "6eacf6c3-8458-43b9-ae03-caf5306d3d53"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
CloudMicrophysics = "6a9e3e04-43cd-43ba-94b9-e8782df3c71b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Coverage = "a2441757-f6aa-5fb2-8edb-039e3f45d037"
CubedSphere = "7445602f-e544-4518-8976-18f8e8ae6cdb"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DispatchedTuples = "508c55e1-51b4-41fd-a5ca-7eb0327d070d"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Formatting = "59287772-0a20-5a39-b81b-1366585eb4c0"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GaussQuadrature = "d54b0c1a-921d-58e0-8e36-89d8069c0969"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
LambertW = "984bce1d-4616-540c-a9ee-88d1112d94c9"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
NonlinearSolvers = "f4b8ab15-8e73-4e04-9661-b5912071d22b"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RootSolvers = "7181ea78-2dcb-4de3-ab41-2b8ab5a31e74"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StaticNumbers = "c5e4b96a-f99f-5557-8ed2-dc63ef9b5131"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Thermodynamics = "b60c26fb-14c3-4610-9d3e-2d17fe7ff00c"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
Adapt = "2.0.2, 3.2"
ArgParse = "1.1"
ArtifactWrappers = "0.1.1"
BenchmarkTools = "0.5"
CUDA = "2.0"
Combinatorics = "1.0"
Coverage = "1.0"
Dierckx = "0.4, 0.5"
DiffEqBase = "6.47"
DispatchedTuples = "0.2"
Distributions = "0.22, 0.23, 0.24"
DocStringExtensions = "0.8"
DoubleFloats = "1.1"
FFTW = "1.2"
FileIO = "1.2"
Formatting = "0.4"
ForwardDiff = "0.10"
GaussQuadrature = "0.5"
JLD2 = "0.1, 0.2, 0.3, 0.4"
KernelAbstractions = "0.4.1, 0.5"
LambertW = "0.4"
LazyArrays = "0.15, 0.16, 0.18, 0.19, 0.20"
Literate = "2.2"
MPI = "0.16, 0.17"
NCDatasets = "0.10, 0.11"
NLsolve = "4.4"
NonlinearSolvers = "0.1"
OrderedCollections = "1.1"
OrdinaryDiffEq = "5.41.0"
PackageCompiler = "1.2"
PrettyTables = "0.9, 0.10, 0.11"
RootSolvers = "0.1, 0.2"
SpecialFunctions = "0.10, 1.0"
StaticArrays = "0.12, 1.0"
StaticNumbers = "0.3.2"
UnPack = "1.0"
WriteVTK = "1.7"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
