# Performance tests to be run by SLURM CI
#
# Each entry specifies the number of MPI ranks to use followed by the file to run

cpu = []

cpu_gpu = [
    { file = "experiments/LES/dycoms.jl", n = 3, args = []},
]

gpu = []

