[deps]
ClimateMachine = "777c4786-024f-11e9-21a3-85d5d4106250"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
GR = "28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[compat]
julia = ">= 1.3"
