name: Coverage

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 2am every day:
    - cron:  '0 2 * * *'

jobs:
  coverage:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        julia-version: ['1.3']
        project: ['ClimateMachine.jl']

    steps:
    - uses: actions/checkout@v1.0.0
    - name: "Set up Julia"
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}

    - name: Install deps
      run: |
        set -o xtrace
        sudo apt-get update
        sudo apt-get install mpich libmpich-dev

    - name: Test with coverage
      env:
        JULIA_PROJECT: "@."
      run: |
        julia --project=@. -e 'using Pkg; Pkg.instantiate()'
        julia --project=@. -e 'using Pkg; Pkg.test(coverage=true)'

    - name: Generate coverage file
      env:
        JULIA_PROJECT: "@."
      run: julia --project=@. -e 'using Pkg; Pkg.add("Coverage");
                                  using Coverage;
                                  LCOV.writefile("coverage-lcov.info", Codecov.process_folder())'
      if: success()
    - name: Submit coverage
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
      if: success()

