name: OS Unit Tests

on:
  push:
    branches:
      - staging
      - trying

jobs:
  test-os:
    timeout-minutes: 210
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    # Workaround for OSX MPICH issue:
    # https://github.com/pmodels/mpich/issues/4710
    env:
      MPICH_INTERFACE_HOSTNAME: "localhost"
      CLIMATEMACHINE_TEST_RUNMPI_LOCALHOST: "true"
      CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.0
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2.2.0
    
    # Setup a filter and only run if src/ test/ folder content changes
    # or project depedencies
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          run_test:
            - 'src/**'
            - 'test/**'
            - 'Project.toml'
            - 'Manifest.toml'


    - name: Set up Julia
      uses: julia-actions/setup-julia@latest
      if: steps.filter.outputs.run_test == 'true'
      with:
        version: 1.6.0

    # https://discourse.julialang.org/t/recommendation-cache-julia-artifacts-in-ci-services/35484
    - name: Cache artifacts
      uses: actions/cache@v1
      if: steps.filter.outputs.run_test == 'true'
      env:
        cache-name: cache-artifacts
      with:
        path: ~/.julia/artifacts 
        key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
        restore-keys: |
          ${{ runner.os }}-test-${{ env.cache-name }}-
          ${{ runner.os }}-test-
          ${{ runner.os }}-

    - name: Install Project Packages
      if: steps.filter.outputs.run_test == 'true'
      run: |
        julia --project=@. -e 'using Pkg; Pkg.instantiate()'

    - name: Build System Image
      if: steps.filter.outputs.run_test == 'true'
      continue-on-error: true
      run: |
        julia --project .dev/systemimage/climate_machine_image.jl ClimateMachine.so true

    - name: Run Unit Tests
      if: steps.filter.outputs.run_test == 'true'
      run: |
        julia --project -J ClimateMachine.so -e 'using Pkg; Pkg.test()'
